In [8]:
# Area and Circumference of circle without module import

#Area of the circle 
r = 4
a = 3.14 * (r**2)
print(a)

#Circumference of the circle
c = 2 * 3.14 * r
print(c)

50.24
25.12


In [9]:
# Area and Circumference of circle with module import

#Import module math for functions and constants
import math

#Area of the circle 
r = 4
a = math.pi * (r**2)  #Use pi constant defined in math module
print(a)

#Circumference of the circle
c = 2 * math.pi * r   #Use pi constant defined in math module
print(c)

50.26548245743669
25.132741228718345


In [10]:
#Selective import of constant pi from math module

from math import pi

In [11]:
#Calculating distance travelled by moon

#Importing function radians for converting degrees to radians
from math import radians

#Approximate distance between center of earth and moon in kms
r = 384400

#Distance travelled by moon if it travels 12 degrees 
dist = r * radians(12)

#Print the distance
print(dist)

80508.54773599443


In [12]:
# List cannot be manipulated directly in the way we want it
l = [1,2,3,4]
l = l * 2
print(l)

[1, 2, 3, 4, 1, 2, 3, 4]


In [13]:
# Manipulating with list is a tedious task
l = [1,2,3,4]
l = list((i*2 for i in l))
l

[2, 4, 6, 8]

In [5]:
#Arrays

#Import Numpy module
import numpy as np

# 1D Array
print("This is how a 1D array looks like.")
one = np.array([1,2,3])
print('Array {}' .format(one))
print('Number of dimensions {}' .format(one.ndim))
print('Type of array {}' .format(type(one)))
print('Shape of array {}' .format(one.shape))
print('Strides used {}' .format(one.strides))
print('Data of array {}' .format(one.data))


This is how a 1D array looks like.
Array [1 2 3]
Number of dimensions 1
Type of array <class 'numpy.ndarray'>
Shape of array (3,)
Strides used (8,)
Data of array <memory at 0x7f352c082948>


In [15]:
# 2D Array
print("This is how a 2D array looks like.")
print("\n")
two = np.array([[1,2,3],[4,5,6]])
print(two)
print("\n")
print(two.ndim)
print("\n")
print(type(two))
print("\n")
print(two.shape)
print("\n")
print(two.strides)
print("\n")

This is how a 2D array looks like.


[[1 2 3]
 [4 5 6]]


2


<class 'numpy.ndarray'>


(2, 3)


(24, 8)




In [16]:
# 3D Array
print("This is how a 3D array looks like.")
print("\n")
three = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three)
print("\n")
print(three.ndim)
print("\n")
print(type(three))
print("\n")
print(three.shape)
print("\n")

This is how a 3D array looks like.


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3


<class 'numpy.ndarray'>


(1, 3, 3)




In [17]:
#Creating array from a list

#Consider the list of heights of baseball players
height_inches = [61,65,63,69,70,73,68,64,63,62]

#Converting this list into numpy array
height_np_inches = np.array(height_inches)
print(height_np_inches)
print(type(height_np_inches))
print(height_np_inches.ndim)
print("\n")

#Converting this array of height to cm
height_np_cm = height_np_inches * 2.54
print(height_np_cm)

[61 65 63 69 70 73 68 64 63 62]
<class 'numpy.ndarray'>
1


[154.94 165.1  160.02 175.26 177.8  185.42 172.72 162.56 160.02 157.48]


In [18]:
#Weight of players in pounds

weight_pounds = [100,200,160,180,140,155,165,172,180,200]

#convert into numpy array
weight_np_pounds = np.array(weight_pounds)
weight_np_kgs = weight_np_pounds * 0.45
print(weight_np_kgs)
print("\n")

height_np_m = height_np_cm / 100
print(height_np_m)
print("\n")

#BMI
bmi = weight_np_kgs / (height_np_m ** 2)
print(bmi)
print("\n")

[45.   90.   72.   81.   63.   69.75 74.25 77.4  81.   90.  ]


[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]


[18.74499852 33.01781751 28.11797007 26.37056314 19.92861129 20.28761798
 24.889215   29.28960936 31.63271633 36.29039516]




In [19]:
#Subsetting a list
x = [4 , 9 , 6, 3, 1]; x[1]

9

In [20]:
#Subsetting arrays
y = np.array(x); y[1]

9

In [21]:
#Boolean method for subsetting
high = y > 5 ;y[high]

array([9, 6])

In [22]:
#Finding out lighter players in our players dataset
light = bmi < 21
print(bmi[light])

[18.74499852 19.92861129 20.28761798]


In [23]:
#Slicing the array
print(weight_np_kgs[2:6])

[72.   81.   63.   69.75]


In [24]:
#Making a 2D array from lists
baseball_total = [weight_np_kgs, height_np_m]
baseball_total_np = np.array(baseball_total)
print(baseball_total_np)
print(baseball_total_np.ndim)
print(baseball_total_np.shape)

[[45.     90.     72.     81.     63.     69.75   74.25   77.4    81.
  90.    ]
 [ 1.5494  1.651   1.6002  1.7526  1.778   1.8542  1.7272  1.6256  1.6002
   1.5748]]
2
(2, 10)


In [25]:
#Looking at the players data at index 2
print(baseball_total_np[0][2],baseball_total_np[1][2])

72.0 1.6002


In [26]:
baseball_total_np[:,2]

array([72.    ,  1.6002])

In [27]:
#Looking at all the players heights
print(baseball_total_np[1])

[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]


In [28]:
#Looking at all the players heights by another approach
print(baseball_total_np[1,:])

[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]


In [29]:
#Arithmatics with arrays
np_mat = np.array([[1, 2], [3, 4], [5, 6]])
np_mat + 10

array([[11, 12],
       [13, 14],
       [15, 16]])

In [30]:
#Transpose
import numpy as np
a = np.array([[2,3,4]])
print(a)
print("\n")
print(a.shape)
print("\n")
a_t = a.T
print(a_t)
print("\n")
print(a_t.shape)

[[2 3 4]]


(1, 3)


[[2]
 [3]
 [4]]


(3, 1)


In [31]:
#Swap axes
import numpy as np
a = np.array([[2,3,4]])
print(a)
print("\n")
print(a.shape)
print("\n")
a = np.swapaxes(a,0,1)
print(a)
print("\n")
print(a.shape)

[[2 3 4]]


(1, 3)


[[2]
 [3]
 [4]]


(3, 1)


In [56]:
#3D array swap axes example
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr_new = np.swapaxes(arr,0,2)
arr_new

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [33]:
#Universal functions
arr = np.arange(10)
print(arr)
print("\n")
#Unary functions
print(np.sqrt(arr)) #Square root
print("\n")
print(np.exp(arr)) # Exponential
print("\n")
x = np.random.randn(8)
print(x)
print("\n")
y = np.random.randn(8)
print(y)
print("\n")
#Binary functions
print(np.maximum(x, y))

[0 1 2 3 4 5 6 7 8 9]


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


[-0.64782318  0.41560283  1.15615657 -0.43821334  0.35782987 -0.12219129
 -0.12248113 -0.05842513]


[-1.05449696 -1.08948091 -0.10345807  0.28182279 -0.06362735  1.83104406
 -1.90092951  0.96312431]


[-0.64782318  0.41560283  1.15615657  0.28182279  0.35782987  1.83104406
 -0.12248113  0.96312431]


In [34]:
#Mathematical and statistical methods
baseball_np = baseball_total_np.T
print(baseball_np)
print(baseball_np.shape)
np_height = baseball_np[:,1]
np_weight = baseball_np[:,0]

[[45.      1.5494]
 [90.      1.651 ]
 [72.      1.6002]
 [81.      1.7526]
 [63.      1.778 ]
 [69.75    1.8542]
 [74.25    1.7272]
 [77.4     1.6256]
 [81.      1.6002]
 [90.      1.5748]]
(10, 2)


In [35]:
#Printing mean of the height 
print(np.mean(np_height))

1.6713200000000001


In [36]:
#Printing mean of the height 
print(np.median(np_height))

1.6383


In [37]:
#Printing sum of weights of all players
print(np.sum(np_weight))

743.4


In [38]:
#Printing cumulative sum of weights of all players
print(np.cumsum(np_weight))

[ 45.   135.   207.   288.   351.   420.75 495.   572.4  653.4  743.4 ]


In [39]:
#Printing cumulative product of weights of all players
print(np.cumprod(np_weight))

[4.50000000e+01 4.05000000e+03 2.91600000e+05 2.36196000e+07
 1.48803480e+09 1.03790427e+11 7.70643923e+12 5.96478396e+14
 4.83147501e+16 4.34832751e+18]


In [40]:
#Printing standard deviation in weight of players
print(np.std(np_weight))

12.667000434199092


In [41]:
#Printing the correlation between the height and weight of the players
print(np.corrcoef(baseball_np[:,0],baseball_np[:,1]))

[[ 1.         -0.01755982]
 [-0.01755982  1.        ]]


In [42]:
#Simple explanation for cummulative sum
a = np.array([0,1,2,3])
print(a.cumsum())

[0 1 3 6]


In [43]:
#Methods for boolean arrays
arr = np.random.randn(100)
print(arr)
print((arr > 0).sum())
print("\n")

#Any and all
bools = np.array([False, False, True, False])
print(bools.any())
print("\n")
print(bools.all())

[ 1.11235589  2.25862663  0.711753   -0.69779055 -0.66100011 -0.38437133
 -0.01236225 -0.83243437 -0.86527332 -1.45911066 -1.26651814 -0.43823386
 -0.33437008  0.06419967  0.07734072 -0.94354065  0.54129518  0.60235917
  0.33119981 -0.08376591  0.31573422 -0.74751779  1.24977442  0.73689711
 -1.32128406 -1.14678521 -0.10608125  0.25122124 -0.06387872  0.16622048
 -0.85139316  1.14077612 -0.58892438 -0.69087905 -0.17968691  0.0025726
 -0.78716147  0.81645143 -1.84204807  0.32908244 -0.79329105 -0.03969608
 -0.26562458  0.31326564  0.56846121  0.46801302 -0.15024467 -0.00371042
 -0.0283293  -0.78613042  0.80612494  1.39079163  0.04341622 -1.86053726
 -0.73913897  1.06600985 -0.49094096 -1.51198623 -0.72032912  0.3264195
  1.93548586 -0.73314177  0.55126438 -0.40078579  0.54402406 -2.17976308
  0.6542304   1.22310407 -0.28464332  0.23846961  0.11626128 -0.25775894
  0.13067511  1.12024188 -1.47838105 -0.55820841 -0.49196908  1.05579556
 -0.03060978 -0.24883045 -0.31805666 -0.73785381  1.0

In [44]:
#Sort
arr = np.random.randn(6)
print(arr)
print("\n")
# print(np.sort(arr))
arr_sorted = np.sort(arr)
print(arr_sorted)

[-0.00421903  0.9391969  -0.40910337  0.58556438  0.75634258 -0.54759016]


[-0.54759016 -0.40910337 -0.00421903  0.58556438  0.75634258  0.9391969 ]


In [45]:
#Unique Function
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [46]:
#File Input and Output with Arrays
arr = np.arange(10)
print(arr)
print("\n")

#Saving the array into file
np.save('DA.npy', arr)

#Loading the file 
np.load('DA.npy')

[0 1 2 3 4 5 6 7 8 9]




array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#Ravel function for flattening of data
arr = np.arange(15).reshape((5, 3))
print("Before changing the ravelled array looking at original array")
print(arr)
print("\n")
rav1 = arr.ravel()
print(rav1)
print("\n")
rav1[0] = 1000
print(rav1)
print("\n")
print("After changing the ravelled array looking at original array")
print(arr)

Before changing the ravelled array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]


After changing the ravelled array looking at original array
[[1000    1    2]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]]


In [48]:
#Flatten function for flattening of data
arr = np.arange(15).reshape((5, 3))
print("Before changing the flattened array looking at original array")
print(arr)
print("\n")
flat1 = arr.flatten()
print(flat1)
print("\n")
flat1[0] = 1000
print(flat1)
print("\n")
print("After changing the flattened array looking at original array")
print(arr)
print("\n")

Before changing the flattened array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]


After changing the flattened array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]




In [49]:
#Concatenation

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print("\n")
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr2)
print("\n")
print(np.concatenate([arr1, arr2], axis=0))
print("\n")
print(np.concatenate([arr1, arr2], axis=1))
print("\n")
print(np.vstack((arr1, arr2)))
print("\n")
print(np.hstack((arr1, arr2)))
print("\n")

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]




In [50]:
#Split
arr = np.random.randn(5, 2)
print("Original array.")
print(arr)
print("\n")
first, second, third = np.split(arr, [1, 2])
print("The first split")
print(first)
print("\n")
print("The second split")
print(second)
print("\n")
print("The third split")
print(third)
print("\n")

Original array.
[[-0.21979475 -1.35494055]
 [-0.01302548  0.47987191]
 [-2.45207718 -0.12218329]
 [ 0.10150393 -0.08771486]
 [ 0.32945504  1.25773952]]


The first split
[[-0.21979475 -1.35494055]]


The second split
[[-0.01302548  0.47987191]]


The third split
[[-2.45207718 -0.12218329]
 [ 0.10150393 -0.08771486]
 [ 0.32945504  1.25773952]]




In [51]:
#Repeat
arr = np.arange(3)
print(arr)
print("\n")
print(arr.repeat(3))

#We can pass list as argument for repeat
print("\n")
print(arr.repeat([2, 3, 4]))
print("\n")

#We can specify axes to do the repeat
arr_2 = np.random.randn(2, 2)
print(arr_2)
print("\n")
print(arr_2.repeat(2, axis=1))

[0 1 2]


[0 0 0 1 1 1 2 2 2]


[0 0 1 1 1 2 2 2 2]


[[ 1.82421551  1.72811428]
 [-2.24804544  0.77959267]]


[[ 1.82421551  1.82421551  1.72811428  1.72811428]
 [-2.24804544 -2.24804544  0.77959267  0.77959267]]


In [52]:
#Tile
print(arr_2)
print(np.tile(arr_2, 2))
print("\n")
print(np.tile(arr_2, (2, 1)))
print("\n")
print(np.tile(arr_2, (3, 2)))

[[ 1.82421551  1.72811428]
 [-2.24804544  0.77959267]]
[[ 1.82421551  1.72811428  1.82421551  1.72811428]
 [-2.24804544  0.77959267 -2.24804544  0.77959267]]


[[ 1.82421551  1.72811428]
 [-2.24804544  0.77959267]
 [ 1.82421551  1.72811428]
 [-2.24804544  0.77959267]]


[[ 1.82421551  1.72811428  1.82421551  1.72811428]
 [-2.24804544  0.77959267 -2.24804544  0.77959267]
 [ 1.82421551  1.72811428  1.82421551  1.72811428]
 [-2.24804544  0.77959267 -2.24804544  0.77959267]
 [ 1.82421551  1.72811428  1.82421551  1.72811428]
 [-2.24804544  0.77959267 -2.24804544  0.77959267]]


In [53]:
#Writing New ufuncs in Python
def add_elements(x, y):
    return x + y

add_them = np.frompyfunc(add_elements, 2, 1) 

print(add_them(np.arange(8), np.arange(8)))


[0 2 4 6 8 10 12 14]


In [54]:
import numpy as np

l = [1,2,3,4,5]

print(l*2)

d = [w*2 for w in l]
print(d)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]


In [55]:
a1 = np.arange(10).reshape(2,5)
print(a1)
print("\n")
print(a1.strides)

[[0 1 2 3 4]
 [5 6 7 8 9]]


(40, 8)


In [19]:
import numpy as np
a=np.linspace(10,15,num=5)
print(a)

[10.   11.25 12.5  13.75 15.  ]
