# numpy limitation

In [4]:
import numpy as np
# type coercion
n1 = np.array([[1, 2, 3], [4, 5, 6]])
print(n1)
n2 = np.array([[1, 2, 3], [4.0, 5.4, 6.2]])
print(n2)
n3 = np.array([[1, 2, 3], [4.0, 5, 'abc']]) 
print(n3)

[[1 2 3]
 [4 5 6]]
[[1.  2.  3. ]
 [4.  5.4 6.2]]
[['1' '2' '3']
 ['4.0' '5' 'abc']]


# Series Data Structure

In [5]:
import pandas as pd

In [6]:
my_data=[10,20,30,40,50]
s1 = pd.Series(my_data,['a', 'b', 'c', 'd', 'e'])
s1 = pd.Series(data=my_data)
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [7]:
import pandas as pd
d={'w':10,'x':20,'y':30,'z':40}      
#dictionary keys act as index and values with every key act as series values
s2 = pd.Series(d)
print(s2)

w    10
x    20
y    30
z    40
dtype: int64


In [8]:
#Addition of two series
#import pandas as pd
ser1=pd.Series([1,2,3,4],['India','Srilanka', 'Bangladesh', 'Russia'])   
ser2=pd.Series([1,2,5,9],['India','Srilanka', 'Bangladesh', 'Russia'])
ser1+ser2

India          2
Srilanka       4
Bangladesh     8
Russia        13
dtype: int64

# DataFrame Data Structure

In [9]:
#Create Dataframe & Select columns
import numpy as np
from numpy.random import randn
np.random.seed(10)
df1=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])  
# df1 generate random number for 5 rows and 4 columns
print(df1)
print(df1['W'])
print(df1[['W','Z']])

          W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805
A    1.331587
B    0.621336
C    0.004291
D   -0.965066
E   -1.136602
Name: W, dtype: float64
          W         Z
A  1.331587 -0.008384
B  0.621336  0.108549
C  0.004291  1.203037
D -0.965066  0.445138
E -1.136602 -1.079805


In [10]:
df1>0

W      X      Y      Z
A   True   True  False  False
B   True  False   True   True
C   True  False   True   True
D  False   True   True   True
E  False   True   True  False

## Data Manipulation: Data selection

In [11]:
#DataFrame.loc() will select rows by index values
#DataFrame.iloc() will select rows by rows numbers
print(df1)
print(df1.loc['A']) # fetch particular row from dataset having index ‘A’
print(df1.iloc[3]) # fetch 3rd row from dataset
print(df1.loc[['A','C'],['X','Z']]) # fetch a subset of data from given dataset

          W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805
W    1.331587
X    0.715279
Y   -1.545400
Z   -0.008384
Name: A, dtype: float64
W   -0.965066
X    1.028274
Y    0.228630
Z    0.445138
Name: D, dtype: float64
          X         Z
A  0.715279 -0.008384
C -0.174600  1.203037


In [12]:
df1

W         X         Y         Z
A  1.331587  0.715279 -1.545400 -0.008384
B  0.621336 -0.720086  0.265512  0.108549
C  0.004291 -0.174600  0.433026  1.203037
D -0.965066  1.028274  0.228630  0.445138
E -1.136602  0.135137  1.484537 -1.079805

In [13]:
# df1.drop('A',axis=0,inplace=False)
#inplace is to True then then it will be affected in the original data structure
df1.drop('W',axis=1,inplace=False)
# df1.drop('W',axis=1,inplace=True)

X         Y         Z
A  0.715279 -1.545400 -0.008384
B -0.720086  0.265512  0.108549
C -0.174600  0.433026  1.203037
D  1.028274  0.228630  0.445138
E  0.135137  1.484537 -1.079805

In [ ]:
print(df1)

In [13]:
from numpy.random import randn
import pandas as pd
np.random.seed(101)
df2=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
print(df2)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [14]:
df2[df2>0]
df2[df2['W']>0][['Y','Z']]
df2

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### set and reset index

In [ ]:
df3=df2.reset_index() #assign natural index
df3=df2.set_index('Z') #set ‘Z’ column as index value
df4 = df3.reset_index()
df4

### Drop missing Values

In [15]:
import pandas as pd
import numpy as np
d={'A':[1,2,np.NaN], 'B':[1,np.NaN,np.NaN],'C':[1,2,3]}     
# np.NaN is the missing element in DataFrame
df4=pd.DataFrame(d)
print(df4)

     A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3


In [ ]:
df4.dropna()         #pandas would drop any row with missing value
df4.dropna(axis=1)   #drop column with NULL value
df4.dropna(thresh=2) #Require <2 non-NA values to drop row.

### Groupby

In [20]:
data = {'Company': [ 'CompA', 'CompA', 'CompB', 'CompB', 'CompC', 'CompC'],
         'Person': ['Rajesh', 'Pradeep', 'Amit', 'Rakesh', 'Suresh', 'Raj'],
         'Sales': [200, 120, 340, 124, 243, 350]}
df6=pd.DataFrame(data)
print(df6)
comp=df6.groupby("Company")             #grouping done using label name “Company”
print(comp.mean())                      #mean appliead on grouped data
comp_std=df6.groupby("Company").std()   #grouping done + standard deviation applied”
comp_std   
df6.groupby("Company").max()            #group dataset based on ‘company’ label and pick maximum value in each labe
df6.groupby("Company").sum().loc["CompB"]
list(comp)

  Company   Person  Sales
0   CompA   Rajesh    200
1   CompA  Pradeep    120
2   CompB     Amit    340
3   CompB   Rakesh    124
4   CompC   Suresh    243
5   CompC      Raj    350
         Sales
Company       
CompA    160.0
CompB    232.0
CompC    296.5


[('CompA',   Company   Person  Sales
  0   CompA   Rajesh    200
  1   CompA  Pradeep    120), ('CompB',   Company  Person  Sales
  2   CompB    Amit    340
  3   CompB  Rakesh    124), ('CompC',   Company  Person  Sales
  4   CompC  Suresh    243
  5   CompC     Raj    350)]

### Finding unique value & number of occurrence from Dataframe

In [22]:
df7 = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
#col1, col2 & col3 are column labels, each column have their own values
df7
df7['col2'].unique()#fetches the unique values available in column
df7['col2'].value_counts()# count number of occurance of every value

444    2
555    1
666    1
Name: col2, dtype: int64

In [26]:
#Type 
print(type(df7['col2']))
print(type(df7[['col2']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


## File Handling

In [24]:
#csv
df1 = pd.read_csv('Data/covid_19_india.csv')
df2 = pd.DataFrame({'C1' : [1, 2, 3], 'C2' : [4, 5, 6], 'C3' : [7, 8, 9]})
print(df2)
df2.to_csv('Data/new.csv')

   C1  C2  C3
0   1   4   7
1   2   5   8
2   3   6   9


In [25]:
df3 = pd.read_excel('Data/Demo.xlsx',sheet_name='Sheet1')
df4 = pd.read_excel('Data/Demo.xlsx',sheet_name='Sheet2')
df5 = pd.DataFrame({'C1' : [1, 1, 1], 'C2' : [2, 2, 2], 'C3' : [3, 3, 3]})
df5.to_excel('Data/new.xlsx', sheet_name='a')